name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Setup Node.js'
        uses: actions/setup-node@v2-beta
        with:
          node-version: '14'

      - name: 'Clone main branch'
        uses: actions/checkout@v2
        with:
          path: main

      - name: 'Build Scriptable files'
        working-directory: main
        run: ./.github/workflows/build.js

      - name: 'Compile README to html'
        working-directory: main
        run: |
          npm i -g showdown
          showdown makehtml -i README.md -o ./.github/workflows/content.html
          sed -e '/\<body\>/r./.github/workflows/content.html' ./.github/workflows/template.html > .deploy/index.html

      - name: 'Clone gh-pages branch'
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh-pages

      - name: 'Prepare for deploy'
        run: mv main/.deploy/* gh-pages/

      - id: check
        name: 'Check if there any changes'
        continue-on-error: true
        run: git diff-index --quiet HEAD --
      
      - name: 'Commit changes'
        if: ${{ steps.check.outcome == 'success' }}
        working-directory: gh-pages
        run: |
          git config --global user.name "$GITHUB_ACTOR"
          git add -A
          git commit -m "ref: $GITHUB_SHA"
      
      - name: 'Push changes'
        if: ${{ steps.check.outcome == 'success' }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          directory: gh-pages
          branch: gh-pages
